### PR TITLE
#975 Incomplete integration tests javadoc

### PR DESCRIPTION
**Pull request by super132**
For #975 
- Adding OAuth scopes requirement for all integration test cases.
- Updating README.md to list down all required OAuth scopes to run integration tests.

### CODE REVIEW

**Comment by super132** [comment]
@dmarkov , please review this PR. Thanks.

**Comment by dmarkov** [comment]
@super132 I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@ggajos please review

**Comment by dmarkov** [comment]
> @dmarkov , please review this PR. Thanks.

@super132 thanks, I'll take a look

**Comment by ggajos** [comment]
@super132 sometimes this scope name is in the same line and sometimes is in next line, let's use some common approach, for example start this new part in next line.

Or maybe we could create annotation like `@IntegrationScope("repo")`; that's just idea, what do you think?

**Comment by super132** [comment]
@ggajos , the information here is to tell developers which OAuth scope shall we need to run execution. I prefer having javadoc over annotation as I am not sure if we have annotation here is just for documentation purpose is a good idea. The up side of using annotation is that developers can use this annotation to validate integration test is runnable with current key, but not sure if it is over-killed in this case.

I am happy to do either one but I personally prefer javadoc if we do not have specific needs of checking like above. What do you think?

**Comment by ggajos** [comment]
@super132 I like the idea of annotation here, it will be harder to overlook. Moreover we might use it as you wrote to validate integration test eventually, but doesn't have to be that way. I would go for annotation here.

**Comment by super132** [comment]
@ggajos , no problem. I will name it as `@OAuthScope` to capture the required scopes. Thanks.

**Comment by super132** [comment]
@ggajos , I have introduced the annotation with `Scope` enum for setting scopes. Please take a look. Thanks.

**Comment by ggajos** [comment]
@super132 Looks very good, thanks

**Comment by ggajos** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@super132 looks good, I like the idea, but we never use these annotations in runtime. I thought that you wanted to use them in order to inform a developer that certain annotation is not supported by his Github account and fail the test with proper message. Now it's not happening. Maybe you can add a puzzle for such a feature?

**Comment by super132** [comment]
@yegor256 yes, that's exactly my idea. I have put the puzzle inside `OAuthScope`. Please take a look. Thanks.

**Comment by super132** [comment]
@yegor256 , may I have your opinion on the latest change? Thanks.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@ggajos I just added **19 mins** to your account, many thanks for your contribution (AP-8G169024EV217051M).. 139 hours and 51 mins spent here. you're getting extra minutes here (c=4). +19 added to your rating, current score is: [+2286](http://www.netbout.com/b/35094?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
