### PR TITLE
For #1487: Use try-with-resource instead try-catch with grizzly.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1487: 
- Use try-with-resource instead try-catch with grizzly in `RtOrganizationTest`, `RtOrganizationsTest`, `RtPaginationTest`, `RtPublicKeysTest`, `RtPublicMembersTest`, `RtPullCommentTest`, `RtPullCommentsTest`, `RtPullTest` and `RtPullsTest.java`
- Left puzzle for continuing implementation

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1488](https://github.com/jcabi/jcabi-github/issues/1488) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/jcabi/jcabi-github/issues/1488#issuecomment-459965432))

@paulodamaso This is what I know about this job in [C9R53K5JA](https://www.0crat.com/p/C9R53K5JA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1488](https://github.com/jcabi/jcabi-github/issues/1488) is [in scope](http://www.zerocracy.com/policy.html#14) for 10days
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C9R53K5JA?q=%7Bjob%3A%27gh%3Ajcabi%2Fjcabi-github%231488%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1488` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1488](https://github.com/jcabi/jcabi-github/issues/1488) is now out of scope

**Pull request merged**
