### PR TITLE
For #1110: Use MkContainers into try-with-resource blocks.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1110:
- Added try-with-resource blocks to close MkContainers after usage, preventing resource leaks
- Replaced try-catch approach in some classes as it was not safe enough (some methods wasn't being covered)
- Left puzzle to continue this issue

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1455](https://github.com/jcabi/jcabi-github/issues/1455) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1455` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1455](https://github.com/jcabi/jcabi-github/issues/1455) is now out of scope

**Pull request merged**
