### PR TITLE
Fix Javadoc link - Issue #984

### PR DESCRIPTION
**Pull request by Marczeeee**
Issue #984

### CODE REVIEW

**Comment by dmarkov** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@carlosmiranda this pull request is for you, please review

**Comment by carlosmiranda** [comment]
@rultor Merge please.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@carlosmiranda Much obliged! I've added **19 mins** to your account in payment "50573539"

+19 added to your rating, current score is: [+1870](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
