### PR TITLE
Travis CI: Test against Java 8

### PR DESCRIPTION
**Pull request by cvrebert**
Would y'all be open to testing against Java 8 too?

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@pinaf please review

**Comment by pinaf** [comment]
@cvrebert looks like it works

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by pinaf** [comment]
@yegor256 looks like a github API limit was reached

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by pinaf** [comment]
@yegor256 same thing
>
403 Forbidden [https://api.github.com/repos/jcabi/jcabi-github/labels]
...
[INFO] {"message":"API rate limit exceeded for 107.20.198.86. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

**Comment by cvrebert** [comment]
@yegor256 Please retry.

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@pinaf I added **19 mins** to your account, many thanks for working with the project! The completion time here was AP-2N997107ST778705N.

review comments (c=4) added as a bonus

added +19 to your rating, now it is equal to [+7757](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
