### PR TITLE
MkIssueLabels.remove: fix "cannpt" [sic] typo

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@longtimeago could you please review this pull request

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge

**Comment by cvrebert** [comment]
@yegor256 The error is irrelevant; please retry.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by cvrebert** [comment]
@yegor256 Error is again unrelated, please try once more.

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@longtimeago paid, thanks, added **16 mins** to your account, payment `55852209`, 48 hours and 31 mins was spent; extra minutes for review comments (c=1); +16 added to your rating, current score is: [+4695](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
