### PR TITLE
Fix typo: User.follwersUrl() [sic]

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@caarlos0 please review, thanks

**Comment by caarlos0** [comment]
@cvrebert maybe we should let the previous method there, with a `@deprecated`, so we don't other people?

@yegor256 what do you think?

**Comment by yegor256** [comment]
@rultor merge it

**Comment by yegor256** [comment]
@caarlos0 nah, it's definitely a bug, let's just fix it

**Comment by cvrebert** [comment]
Error is unrelated:
```
Failed tests:
RtContentsITCase.canUpdateFileContentInSpecificBranch:146 HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/repos/jcabi-github-test2/0E93sBLCMI/contents/TIQBzjsVhL]
[...]
Tests run: 113, Failures: 1, Errors: 0, Skipped: 5
```

**Comment by caarlos0** [comment]
@yegor256 OK.

**Comment by cvrebert** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@caarlos0 Thanks so much! Your account was topped up for **17 mins** (transaction ID is `AP-4WK17130S4037323A`, the task took 22 hours and 49 mins). you're getting extra minutes here (c=2). added +17 to your rating, now it is equal to [+1996](http://www.netbout.com/b/35095?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
