### PR TITLE
For #1469: Added reaction tests for pull comments.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1469: Added reaction tests for pull comments.
- Added `Reaction` methods to `PullComment`;
- Added tests to assure the implementation is correct

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1475](https://github.com/jcabi/jcabi-github/issues/1475) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1475](https://github.com/jcabi/jcabi-github/issues/1475) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/929da7a7-5b84-4ae7-916a-9c1792e21404); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/jcabi/jcabi-github/issues/1475#issuecomment-454664991))

@g4s8 This is what I know about this job in [C9R53K5JA](https://www.0crat.com/p/C9R53K5JA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1475](https://github.com/jcabi/jcabi-github/issues/1475) is [in scope](http://www.zerocracy.com/policy.html#14) for 12hr
  * The role is `REV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [12hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C9R53K5JA?q=%7Bjob%3A%27gh%3Ajcabi%2Fjcabi-github%231475%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by amihaiemil** [comment]
@rultor merge it

**Pull request merged**
