### PR TITLE
RtRepoTest.fetchesGit method have no @Test annotation #916

### PR DESCRIPTION
**Pull request by lthuangiang**

### CODE REVIEW

**Comment by yegor256** [comment]
@lthuangiang are you planning to finish this pull request? If not, please close it

**Comment by cvrebert** [comment]
@yegor256 This is [already fixed in current `master`](https://github.com/jcabi/jcabi-github/blob/master/src/test/java/com/jcabi/github/RtRepoTest.java#L273), so this PR should just be closed.

**Comment by yegor256** [comment]
right, closing

**Comment by dmarkov** [comment]
@yegor256 **19 mins** was added to your account, many thanks for your contribution! The task took 000-c9062e71.; you're getting extra minutes here (c=4); added +19 to your rating, now it is equal to [+8556](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
