### PR TITLE
#1509 checkstyle, renaming and a little refactoring

### LINKED ISSUE #1509: Fix checkstyle for PR 1508
Fix checkstyle errors for PR #1508. See [here](https://travis-ci.org/jcabi/jcabi-github/builds/639027560#L2082)

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #1509 

* Renamed method ``contains`` to ``exists`` and declared it in the interface;
* Removed useless json body from the GET operation
* Fixed checkstyle errors
* Added the method in ``MkRepos`` as well, currently throwing UnsupportedOperationException.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@ShalomGottesman Pls have a look at my changes to your method, I hope it's ok with you.

I had to also declare the method in the Repos interface, otherwise you will not be able to use it. 
This is becuase users do not have access to the class ``RtRepos`` (it is package-protected), they work solely through the ``Repos`` interface.

**Comment by ShalomGottesman** [comment]
Originally I had the thought to declare the method also in the Repos interface, but did not know how to implement that in the MkRepos class. As such, I didn't want to submit the changes that would break the build.

**Comment by amihaiemil** [comment]
@ShalomGottesman For future reference, you can just implement it and make it throw ``UnsupportedOperationException``, then open a new Issue for its implementation. :D

**Comment by amihaiemil** [comment]
@ShalomGottesman By the way, we still cannot release a new version because Rultor is still broken:( 

I'll let you know as soon as the new version is released. Until then, if you like, feel free to open other PRs :)

**Comment by ShalomGottesman** [comment]
Good to know!

**Comment by 0crat** [comment]
Job [#1512](https://github.com/jcabi/jcabi-github/issues/1512) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1512` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1512](https://github.com/jcabi/jcabi-github/issues/1512) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by ShalomGottesman** [comment]
@amihaiemil Any update on when v1.1 will be released?

**Pull request merged**
