### PR TITLE
Add missing Issue Event type constants

### LINKED ISSUE #1024: Missing issue event types
The list of issue event type constants on http://github.jcabi.com/apidocs-0.21.3/com/jcabi/github/Event.html#field_summary seems to be missing several entries when compared against [the GitHub API docs](https://developer.github.com/v3/issues/events/#events-1), specifically:
* unassigned
* labeled
* unlabeled
* milestoned
* demilestoned
* renamed
* locked
* unlocked

I believe constants for these should be added.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #1024.

### CODE REVIEW

**Comment by dmarkov** [comment]
I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@longtimeago this pull request is for you, please review

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@longtimeago thanks, I just added **16 mins** to your account, payment `54237712`, 47 hours and 18 mins spent

extra minutes for review comments (c=1)

+16 added to your rating, at the moment it is: [+3739](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
