### PR TITLE
Fix wrong @see links in JavaDocs for Organization & Users

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@longtimeago could you please review this pull request

**Comment by longtimeago** [comment]
@cvrebert minor fix, but anyway ... Thank you!

**Comment by longtimeago** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by cvrebert** [comment]
Same errors as https://github.com/jcabi/jcabi-github/pull/1100#issuecomment-108114012

**Comment by cvrebert** [comment]
The errors are due to #1104.

**Comment by cvrebert** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by cvrebert** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge again

**Pull request merged**
