### PR TITLE
For #1225: Fixed bug in calling github emoji API

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1225: Corrected test in `RtGithubTest`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1453](https://github.com/jcabi/jcabi-github/issues/1453) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1453` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1453](https://github.com/jcabi/jcabi-github/issues/1453) is now out of scope

**Pull request merged**
