### PR TITLE
Migrate to Junit 5

### PR DESCRIPTION
**Pull request by andreoss**
- Migrate to Junit 5
- Temporarily disable PMD and XML checks (until parent is updated)

### CODE REVIEW

**Comment by amihaiemil** [comment]
@andreoss why is this migration needed? It's a PR with 200+ changed files, it's unacceptable, sorry.

**Comment by amihaiemil** [comment]
@andreoss please open a ticket, discuss with @yegor256 (he's the project owner) and if you come to an agreement add the JUnit 5 setup, which will be used in **future tests**. I would not change existing tests...

**Comment by andreoss** [comment]
@amihaiemil
It was supposed to be for #1544, essentially it means
1) upgrading qulice
2) upgrading junit to 5
3) upgrading parent

1) and 2) involve a lot of changes, but they are done by a script.
The changes are trivial, with an exception of handful of `@Text(expected = ...)` cases.

**Comment by amihaiemil** [comment]
@andreoss the tests in jcabi-github are already quite unstable (especially the integration tests calling the Github API). I'm really no confortable with this many changes...

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1552` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#1552](https://github.com/jcabi/jcabi-github/issues/1552) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
