### PR TITLE
Implementing MkRepos exists

### LINKED ISSUE #1511: Implement MkRepos.exists(...)
We should implement the mock version of Repos.exists(...). Don't forget to also test it.

### PR DESCRIPTION
**Pull request by maviteixeira**
Fixes #1511

Implemented MkRepos.exists()

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1515](https://github.com/jcabi/jcabi-github/issues/1515) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@maviteixeira looks good, thank you very much!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1515` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1515](https://github.com/jcabi/jcabi-github/issues/1515) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by maviteixeira** [comment]
> @maviteixeira looks good, thank you very much!

My pleasure : )

**Pull request merged**
