### PR TITLE
Incorrect documentation - example integration test run script #976

### PR DESCRIPTION
**Pull request by nhekfqn**

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@longtimeago please review this one

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by nhekfqn** [comment]
@rultor Please stand by, there is a merge conflict.

**Comment by nhekfqn** [comment]
@longtimeago merge conflict resolved. Please review.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by nhekfqn** [comment]
@rultor @yegor256 same issue as yesturday

Failed tests: RtRepoITCase.iteratesLanguages:163 Expected: not an empty iterable but: was <[]>

Until the issue is fixed we should just try to merge again.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by nhekfqn** [comment]
@rultor @yegor256 Same issue. Another try?

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@rultor deploy pls

**Comment by dmarkov** [comment]
@longtimeago Much appreciated! **15 mins** was added to your account, payment ID `50907208`. +15 to your rating, your total score is [+1445](http://www.netbout.com/b/35024?open=rating)

**Pull request merged**
