### PR TITLE
Issue milestone

### PR DESCRIPTION
**Pull request by g4s8**
#1065 - added milestone to `Issue.Smart` and integration tests

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#1353](https://github.com/jcabi/jcabi-github/issues/1353) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/jcabi/jcabi-github/issues/1353#issuecomment-370892137))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1353](https://github.com/jcabi/jcabi-github/issues/1353) is [in scope](http://www.zerocracy.com/policy.html#14) for 21hr
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3RUBL5H9?q=%7Bjob%3A%27gh%3Ajcabi%2Fjcabi-github%231353%27%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/jcabi/jcabi-github/issues/1353#issuecomment-370892137))

@g4s8 You need to have one of these roles in order to do what you're trying to do: `ARC`, `PO`. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "g4s8").

**Comment by g4s8** [comment]
@yegor256 please, take a look here, looks like nobody assigned as `REV`

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/jcabi/jcabi-github/issues/1353#issuecomment-370892842). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 could you please make a release with this changes?

**Comment by yegor256** [comment]
@rultor release, tag is `0.35`

**Comment by 0crat** [comment]
The job [#1353](https://github.com/jcabi/jcabi-github/issues/1353) is now out of scope

**Pull request merged**
