### PR TITLE
Adding Repos.exists IT test.

### LINKED ISSUE #1510: Add tests for RtRepos.exists(...)
We should add unit and integration tests for method RtRepos.exists(...);

### PR DESCRIPTION
**Pull request by maviteixeira**
PR for #1510 

New IT test for Repos.exists.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@maviteixeira looks great, thanks!

Let's not close the Issue yet, until the bot assigns it to you,
so you get the points.

**Comment by maviteixeira** [comment]
@amihaiemil  Great, thank you.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1524` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
