### PR TITLE
get github key from a unit class while do tests

### LINKED ISSUE #973: Multiple use of the same hardcoded string
In the process of investigating  #963 I found that failsafe.github.key property is accessed via System.getProperty call with the same hardcoded string literal. This doesn't look like a good design.

### PR DESCRIPTION
**Pull request by wb14123**
This fixes #973

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@krzyk please review

**Comment by krzyk** [comment]
@wb14123 I think the idea was to use [ExternalResource](http://junit.org/javadoc/latest/org/junit/rules/ExternalResource.html) from JUnit, not to create a static class. This way you could provide right away Gists or Repos object, not just the String with API.

**Comment by krzyk** [comment]
@wb14123 Just a reminder, how is it going?

**Comment by krzyk** [comment]
@wb14123 ping

**Comment by krzyk** [comment]
@wb14123 please close this PR if you are not working on it

**Comment by krzyk** [comment]
@wb14123 ping

**Comment by dmarkov** [comment]
@krzyk Thanks so much! Your account was topped up for **19 mins** (transaction ID is `52423666`)... you're getting extra minutes here (c=4)... +19 to your rating, your total score is [+4439](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
