### PR TITLE
For #1477: Added  reaction code to issues

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1477:
- Added reaction code to issue
- Changed tests that were malfunctioning
- Removed todo

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1485](https://github.com/jcabi/jcabi-github/issues/1485) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1485` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1485](https://github.com/jcabi/jcabi-github/issues/1485) is now out of scope

**Pull request merged**
