### PR TITLE
For #1086: Get branch by name API

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1086:
- Added fake method `find(name)` to `Branches`
- Added test to assert `find(name)` correct behavior
- Left puzzle to implement `find(name)` according to test

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1454](https://github.com/jcabi/jcabi-github/issues/1454) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@amihaiemil Something very bad went here, 0crat shouldn't be allowed to assign this PR to me

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/jcabi/jcabi-github/issues/1454#issuecomment-448582462))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#1454](https://github.com/jcabi/jcabi-github/issues/1454), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by amihaiemil** [comment]
@paulodamaso looks good, thanks! :)

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1454` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1454](https://github.com/jcabi/jcabi-github/issues/1454) is now out of scope

**Pull request merged**
