### PR TITLE
add collaborator with permissions

### PR DESCRIPTION
**Pull request by ShalomGottesman**
Added: 
1. Enum to collaborators interface of permissions types
2. A new method in collaborators interface to add collaborator with permissions
3. Implemented method in RtCollaborators.java
4. Throws unimplemented exception in MkCollaborators.java

I do not remember which exception is usually used to show if something is unimplemented. I chose one from apache commons. If a different one is usually used then change it

### CODE REVIEW

**Comment by amihaiemil** [comment]
@ShalomGottesman PR looks ok, but qulice commplains about code style issues. Please, fix them, otherwise I cannot merge the PR.

**Comment by ShalomGottesman** [comment]
@amihaiemil Corrections checked in

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1532` is not assigned, can't get performer

**Pull request merged**
