### PR TITLE
feat(#1658): Add Coordinates.Https implementation

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add `Coordinates.Https` implementation.

Closes: #1658

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you release new minor version, please?

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `1.1.0`, title is `1.1.0`

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Pull request merged**
