### PR TITLE
Update dependencies to latest #1188

### PR DESCRIPTION
**Pull request by JimDeanSpivey**
Issue: #1188 

mvn clean install -Pqulice passes. I had to change javax.ws.rs to compile, it was defaulting to provided after being updating jersey to latest, and failed the build.

### CODE REVIEW

**Comment by JimDeanSpivey** [comment]
@dmarkov CR needed.

**Comment by dmarkov** [comment]
@jimdeanspivey Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request closed without merging**
