### PR TITLE
Upgrade to jcabi-http 1.11

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Many thanks! **16 mins** were added to your account in Transaction ID `000-5309f0a9` (task took 21 hours and 19 mins). review comments (c=1) added as a bonus. +16 added to your rating, at the moment it is: [+5898](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
