### PR TITLE
#1323 - MkIssue isPull

### PR DESCRIPTION
**Pull request by g4s8**
#1323: Fixed `MkIssue` json if it's a pull request

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1324` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+525](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 in Rultor's build logs too many github failures like this:
```
Expected: HTTP response with status 204
     but: was <403 Forbidden
{
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 could you please release with this changes?

**Comment by yegor256** [comment]
@g4s8 will do now: https://github.com/jcabi/jcabi-github/issues/1323#issuecomment-334077952

**Pull request merged**
