### PR TITLE
(#1305) Implemented MkUser.notifications()

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* solves #1305 
* Implements `MkUser.notifications()`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1374](https://github.com/jcabi/jcabi-github/issues/1374) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@llorllale Well, it's not entirely correct, but it's not your fault. Truth is they got lazy with the Mock implementation of the library, it has many parts not ok.

The Mk implementations should be live objects, animating that ``Storage`` and reflecting the consequences of actions on it. For instance, these to mock users:

```java
//pseudocode

final Storage storage = new MkStorage(...);
final Github mihai = new MkGithub("amihaiemil", storage);
final Github george = new MkGithub("llorllale", storage);

//mihai leaves a comment in one of george's repos

george.self().notifications()//should have size 1 automatically, as a consequence of mihai leaving a comment.
```

This mechanism works fine with Issue/Comments, for instance. in the code above, if ``mihai`` leaves a comment in one of the ``Issue``s from ``george``'s ``Repo``, it will be visible when ``george`` iterates over them. 

But again, it's not your fault, I see ``Notification`` is also poorly implemented in the real api: see [RtNotification](https://github.com/jcabi/jcabi-github/blob/647243cc5f0451398fde2fbccd7cb50a29dcdfa1/src/main/java/com/jcabi/github/RtNotification.java): it's a dumb data holder instead of a real api Notification, like Comment for instance. Also, if you ask me, ``markAsRead`` should be an operations on ``Notifications`` (plural), not on ``User``... we don't even have ``Notifications``. 

This said, maybe you can open an Issue to revise the mock implementation somehow, fix where we can (not necessarily this Notification part, there are other parts as well). But I don't know when we find the time to do it.

**Comment by 0crat** [comment]
This pull request [#1374](https://github.com/jcabi/jcabi-github/issues/1374) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C9R53K5JA/941465149); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1374](https://github.com/jcabi/jcabi-github/issues/1374) is now out of scope

**Pull request merged**
