### PR TITLE
feat: get default branch from repo

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
According with [that doc](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository) we can get `default_branch` from any repo:
```json
{
//..
"forks_count": 9,
"stargazers_count": 80,
"watchers_count": 80,
"size": 108,
"default_branch": "master",
//...
}
```

It could be useful for some cases (like [that](https://github.com/yegor256/rultor/issues/1302)) to get a default repo branch.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Can you have a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `1.4.0`

**Comment by yegor256** [comment]
@volodya-lombrozo thanks a lot, try new version 1.4.0

**Pull request merged**
