### PR TITLE
Bug #1362: MkRelease.create(tag) no longer prepopulates 'name' and 'body' with junk values

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* solves #1362 
* MkReleases.create(String tag) no longer prepopulates the 'name' and 'body' attributes with junk values

I used [this release](https://github.com/llorllale/test/releases/tag/0.1.0) as reference. I created it via the web interface and only specified the tag. Everything else was left with defaults. This is the API's response:

```json
[
  {
    "url": "https://api.github.com/repos/llorllale/test/releases/10117128",
    "assets_url": "https://api.github.com/repos/llorllale/test/releases/10117128/assets",
    "upload_url": "https://uploads.github.com/repos/llorllale/test/releases/10117128/assets{?name,label}",
    "html_url": "https://github.com/llorllale/test/releases/tag/0.1.0",
    "id": 10117128,
    "tag_name": "0.1.0",
    "target_commitish": "master",
    "name": "",
    "draft": false,
    "author": {
      "login": "llorllale",
      "id": 2019896,
      "avatar_url": "https://avatars1.githubusercontent.com/u/2019896?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/llorllale",
      "html_url": "https://github.com/llorllale",
      "followers_url": "https://api.github.com/users/llorllale/followers",
      "following_url": "https://api.github.com/users/llorllale/following{/other_user}",
      "gists_url": "https://api.github.com/users/llorllale/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/llorllale/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/llorllale/subscriptions",
      "organizations_url": "https://api.github.com/users/llorllale/orgs",
      "repos_url": "https://api.github.com/users/llorllale/repos",
      "events_url": "https://api.github.com/users/llorllale/events{/privacy}",
      "received_events_url": "https://api.github.com/users/llorllale/received_events",
      "type": "User",
      "site_admin": false
    },
    "prerelease": false,
    "created_at": "2018-03-16T06:16:25Z",
    "published_at": "2018-03-16T06:16:42Z",
    "assets": [

    ],
    "tarball_url": "https://api.github.com/repos/llorllale/test/tarball/0.1.0",
    "zipball_url": "https://api.github.com/repos/llorllale/test/zipball/0.1.0",
    "body": ""
  }
]
```

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#1368](https://github.com/jcabi/jcabi-github/issues/1368) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#1368](https://github.com/jcabi/jcabi-github/issues/1368) is now out of scope

**Pull request merged**
