### PR TITLE
respect-limits docs: Fix links to API docs

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@ggajos please review, thanks

**Comment by ggajos** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@ggajos I just added **16 mins** to your account, many thanks for your contribution.. AP-9AW92070MP089763D spent here. review comments (c=1) added as a bonus. +16 added to your rating, at the moment it is: [+3344](http://www.netbout.com/b/35094?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
