### PR TITLE
Fix Rultor build by using --no-rdoc --no-ri instead of -N

### PR DESCRIPTION
**Pull request by cvrebert**
See https://github.com/jcabi/jcabi-github/pull/1100#issuecomment-110250596
Refs #1103.

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@cvrebert thanks

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-e9a87dfa`, task took 23 hours and 33 mins to complete... review comments (c=1) added as a bonus... +16 added to your rating, current score is: [+6681](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
