### PR TITLE
Removed puzzle left over from #1439

### PR DESCRIPTION
**Pull request by llorllale**
I forgot to delete the puzzle for #1439 (PR was #1441)

### CODE REVIEW

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please review this and merge or reject

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1443` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
