### PR TITLE
#1363 json boolean read fixed

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #1363

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1386](https://github.com/jcabi/jcabi-github/issues/1386) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1386](https://github.com/jcabi/jcabi-github/issues/1386) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/1041340829); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by llorllale** [comment]
@amihaiemil please add some tests.

Your solution seems better than mine though: I overlooked the overload on `getBoolean` that *didn't* throw a ClassCastException if the JsonValue was not boolean.

**Comment by amihaiemil** [comment]
@llorllale right, I'll look into it tomorrow, probably :D

**Comment by amihaiemil** [comment]
@llorllale done :)

**Comment by llorllale** [comment]
@amihaiemil can you please add a couple of tests where `prerelease` is mapped to a *string* "false" or "true"? Just to make sure it will work with `MkRelease`.

**Comment by amihaiemil** [comment]
@llorllale I added your test and it still fails... I left a puzzle, it's too much work already

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1386](https://github.com/jcabi/jcabi-github/issues/1386) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
