### PR TITLE
For #1467: Implement reaction validation

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1467: 
- Implemented reaction validation test for invalid reactions
- Left puzzle for validation implementation

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1478](https://github.com/jcabi/jcabi-github/issues/1478) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@paulodamaso small conflict now :)

**Comment by paulodamaso** [comment]
@amihaiemil done!

**Comment by paulodamaso** [comment]
@amihaiemil Corrected violations, please take a look

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1478` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1478](https://github.com/jcabi/jcabi-github/issues/1478) is now out of scope

**Pull request merged**
