### PR TITLE
For #1490: Continued to close grizzle servers open on tests.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1490: Continued to close grizzle servers open on tests.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1491](https://github.com/jcabi/jcabi-github/issues/1491) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1491` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1491](https://github.com/jcabi/jcabi-github/issues/1491) is now out of scope

**Pull request merged**
