### PR TITLE
RtRepos can now check if repository exists from this entry

### PR DESCRIPTION
**Pull request by ShalomGottesman**
All yes, except last one. same issue as last time when trying to build but I tested this method separately in my own code.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@ShalomGottesman looks ok, thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1508` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job [#1508](https://github.com/jcabi/jcabi-github/issues/1508) is now in scope, role is `REV`

**Comment by 0crat** [comment]
The job [#1508](https://github.com/jcabi/jcabi-github/issues/1508) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
