### PR TITLE
Upgrade to com.jcabi.jcabi 1.19

### PR DESCRIPTION
**Pull request by cvrebert**
We pray that this will fix https://github.com/jcabi/jcabi-github/pull/1131#issuecomment-114334608
Refs https://github.com/jcabi/jcabi/pull/304

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by cvrebert** [comment]
@yegor256 Please, try tagging a release again.

**Comment by yegor256** [comment]
@rultor release, tag is `0.24`

**Comment by cvrebert** [comment]
Yay!

**Comment by yegor256** [comment]
@cvrebert I just suppressed site-deployment failures in `.rultor.yml`. it still fails :( would be great to fix it

**Pull request merged**
