### PR TITLE
For #1483: Added reaction validation.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1483:
- Added validation to `RtReaction`
- Removed ignore from test
- Removed todo

### CODE REVIEW

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/jcabi/jcabi-github/issues/1489#issuecomment-459965462))

@paulodamaso This is what I know about this job in [C9R53K5JA](https://www.0crat.com/p/C9R53K5JA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1489](https://github.com/jcabi/jcabi-github/issues/1489) is [in scope](http://www.zerocracy.com/policy.html#14) for 10days
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C9R53K5JA?q=%7Bjob%3A%27gh%3Ajcabi%2Fjcabi-github%231489%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1489` is not assigned, can't get performer

**Pull request merged**
