### PR TITLE
#956 done. added corresponding test

### PR DESCRIPTION
**Pull request by apocarteres**
please check and approve

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@yegor256 it's yours, please review

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by apocarteres** [comment]
fixed duplicate puzzle. please try to merge it again

**Comment by yegor256** [comment]
@rultor merge

**Comment by apocarteres** [comment]
hm.. have no idea yet, what's wrong this time. Just a couple thoughts:

1. OOME on rultor backend? Needs to be checked the logs on rultor box
2. Last run took ~2hr, it could be prime time for rultor and it didn't manage to get all tasks done

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@rultor try to merge again

**Pull request closed without merging**
