### PR TITLE
Fix JavaDoc copypasta of some instance vars

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by dmarkov** [comment]
@yegor256 No messages from you above, won't pay for now. If I'm wrong, correct me.

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Comment by dmarkov** [comment]
@cvrebert the code made here contains a puzzle `1126-bb836510`/#1130, which will be resolved soon

**Comment by cvrebert** [comment]
@yegor256 It seems that @dmarkov has attributed that puzzle to the wrong PR.

**Comment by yegor256** [comment]
@cvrebert looks like it's your fault :) see https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtStatuses.java#L121

**Comment by 0pdd** [comment]
@cvrebert the puzzle [#1561](https://github.com/jcabi/jcabi-github/issues/1561) is still not solved.

**Comment by 0pdd** [comment]
@cvrebert 2 puzzles [#1130](https://github.com/jcabi/jcabi-github/issues/1130), [#1783](https://github.com/jcabi/jcabi-github/issues/1783) are still not solved.

**Pull request merged**
