### PR TITLE
#1036 Correct repositories GET

### PR DESCRIPTION
**Pull request by eekysam**
Change the URI path so that the list public repositories query works.

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@darkled please review

**Comment by darkled** [comment]
@eekysam the build didn't pass quality checks:
```
[ERROR] \src\main\java\com\jcabi\github\RtRepos.java[130]: Line is longer than 80 characters (found 90). (LineLengthCheck)
```
Could you please fix it?

**Comment by darkled** [comment]
@eekysam any progress here?

**Comment by eekysam** [comment]
I just threw together my own system due to some other problems, so no, I haven't made any progress. But It is literally a single missed call, you don't really need a pull to fix it, I only requested one so you would know what to change. It would be more work to merge this in than to just add the function call and commit.

**Comment by dmarkov** [comment]
@darkled Thanks for your contribution, **17 mins** was added to your account, payment ID is `54991565`, 145 hours and 24 mins spent total

extra minutes for review comments (c=2)

added +17 to your rating, now it is equal to [+2366](http://www.netbout.com/b/35091?open=rating)

**Pull request closed without merging**
