### PR TITLE
Don't bother generating docs when installing pdd

### PR DESCRIPTION
**Pull request by cvrebert**
This should speed up the build a little bit and avoid some unnecessary console output.

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@ggajos please review this PR

**Comment by cvrebert** [comment]
@yegor256 Does this really need non-architect review? It's trivial.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by cvrebert** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by cvrebert** [comment]
@yegor256 Apparently this [broke the build](http://www.rultor.com/t/4022-110252222). The error message would seem to indicate that an old version of `gem` or `ruby` is being used, hence this relatively new option isn't supported; see https://github.com/rails/rails-dev-box/issues/84#issuecomment-64671808
Is it feasible to upgrade, or should we revert this change?

**Comment by cvrebert** [comment]
Ah, nvm, just saw https://github.com/jcabi/jcabi-github/pull/1100#issuecomment-110250596

**Pull request merged**
