### PR TITLE
For #1447: Make `JsonNode` return `JsonArray` correctly

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1447:
- Corrected method `JsonNode.json()`
- Removed `@Ignore` from tests and changed tests where needed

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1452](https://github.com/jcabi/jcabi-github/issues/1452) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1452` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1452](https://github.com/jcabi/jcabi-github/issues/1452) is now out of scope

**Pull request merged**
