### PR TITLE
Add Search.Qualifier.TEAM

### LINKED ISSUE #1025: Missing Search.Qualifier value: "team"
Per [the relevant GitHub API docs](https://developer.github.com/v3/search/#search-issues), GitHub supports a `team` qualifier for issue searches. The `com.jcabi.github.Search.Qualifier` enum seems to be missing a corresponding `TEAM` value.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #1025.

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@pinaf could you please review this pull request

**Comment by pinaf** [comment]
@cvrebert is the idea here just to add the enum entry? no actual use of it in the API query?

**Comment by cvrebert** [comment]
@pinaf Correct.

**Comment by pinaf** [comment]
@cvrebert what is the point of that?

**Comment by cvrebert** [comment]
The same as for all the other values of this enum. To facilitate the use of named constants instead of repetitive, possibly misspelled, literal strings, and also allow for better typechecking. To make it clear what the universe of available search qualifiers is. To be comprehensive in representing GitHub's available API.

**Comment by pinaf** [comment]
@cvrebert sure, my question was more to the sense of why add it without any use - not why you should use enums.

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by pinaf** [comment]
@cvrebert thanks!

**Comment by dmarkov** [comment]
@pinaf Thanks a lot, I just topped your account for **20 mins**, transaction ID `AP-9DH42254329519737`, total time was 24 hours and 1 min; review comments (c=5) added as a bonus; +20 added to your rating, at the moment it is: [+5993](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
