### PR TITLE
Fix javadoc descriptions of some Pull.Smart methods

### PR DESCRIPTION
**Pull request by cvrebert**
Looks like some copypasta mistakes.

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@carlosmiranda please review this PR

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by cvrebert** [comment]
@yegor256 Please retry merge. Error was unrelated and probably transient:
```
Failed tests: RtContentsITCase.canUpdateFileContent:102 HTTP response status is not equal to 200: 404 Not Found [https://api.github.com/repos/jcabi-github-test2/BgekXK1xtW/contents/eoAEwM95ZY]
```

**Comment by yegor256** [comment]
@rultor try to merge again

**Pull request merged**
