### PR TITLE
For #1466: Reaction implementation tests for Issue

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1466: Reaction implementation tests for Issue
- Added test for `RtIssue` regarding `Reaction` feature
- Added puzzle to continue with implementation

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1471](https://github.com/jcabi/jcabi-github/issues/1471) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@paulodamaso can you fix the conflict, so we can merge this PR?

**Comment by paulodamaso** [comment]
@amihaiemil sorry for the delay, take a look

**Comment by 0crat** [comment]
The job [#1471](https://github.com/jcabi/jcabi-github/issues/1471) is now out of scope

**Pull request merged**
