### PR TITLE
For #1244: Remove gravatar support.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1244: Remove gravatar support from `User` and `RtUserTest.`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1448](https://github.com/jcabi/jcabi-github/issues/1448) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@amihaiemil There is something wrong with travis ci?

**Comment by 0crat** [comment]
This pull request [#1448](https://github.com/jcabi/jcabi-github/issues/1448) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C9R53K5JA/50296a63-74bb-4740-9b6d-af5da9a47b93); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
The job [#1448](https://github.com/jcabi/jcabi-github/issues/1448) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
