### PR TITLE
#997 added license

### PR DESCRIPTION
**Pull request by apocarteres**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@krzyk please review, thanks

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@krzyk I just added **15 mins** to your account, many thanks for your contribution..; +15 added to your rating, at the moment it is: [+3478](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
