### PR TITLE
(#1399) Randomized port used for some tests

### PR DESCRIPTION
**Pull request by llorllale**
This PR:

* Solves #1399 
* Leaves puzzle for the rest

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1402](https://github.com/jcabi/jcabi-github/issues/1402) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by llorllale** [comment]
@amihaiemil ping

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#1402](https://github.com/jcabi/jcabi-github/issues/1402) is now out of scope

**Pull request merged**
