### PR TITLE
Fix incorrect javadocs for 3 Issue.Smart methods

### PR DESCRIPTION
**Pull request by cvrebert**
Looks like copypasta gone wrong or something.

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@longtimeago please review this PR

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@longtimeago done, I added **16 mins** in payment `55912921`, 93 hours and 18 mins spent to complete this

extra minutes for review comments (c=1)

+16 added to your rating, at the moment it is: [+4714](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
