### PR TITLE
Add pagination support to pull request files

### PR DESCRIPTION
**Pull request by gjacquet**
Pull request files are paginated: https://developer.github.com/v3/pulls/#list-pull-requests-files

Adding support to fetch all file pages.

### CODE REVIEW

**Comment by dmarkov** [comment]
@gjacquet Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by gjacquet** [comment]
Any feedback?

**Comment by amihaiemil** [comment]
@gjacquet hey (and sorry for the almost 2-year wait)

I'm not sure what this PR does. First of all, there is no test case to cover these changes :)

Do you remember, is there any open Issue for it? Where the actual and expected behaviour are describer?

**Comment by gjacquet** [comment]
I don't think there was an issue opened :thinking: 
It's actually pretty simple. The list of files part of a pull request can be pretty long sometimes and is paginated by github. Currently, this library only fetches the first page.

I made a quick fix to allow fetching all the pages.

**Comment by amihaiemil** [comment]
@gjacquet I see... well, it looks fine, let's try to merge

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by gjacquet** [comment]
Thanks @amihaiemil!

**Pull request merged**
