### PR TITLE
Add "Cheks" classes

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I have added several classes to the codebase, including:
- `Checks` interface
- `Check` interface
- `RtChecks` class, which implements the `Checks` interface
- `RtCheck` class, which implements the `Check` interface
The PR may seem large due to the addition of excessive JavaDocs. Additionally, I am unsure about the overall design of the added classes.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@rultor merfge

**Comment by yegor256** [comment]
@rultor release, tag is `1.5.0`

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!

**Pull request merged**
