### PR TITLE
For #1442: JsonNode should return JSonArray

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1442: 
- Added test to ensure JsonNode will return correct JsonArray when xml has similar structure;
- Updated todo.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1444](https://github.com/jcabi/jcabi-github/issues/1444) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1444](https://github.com/jcabi/jcabi-github/issues/1444) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/73a7c5ea-915e-4bb7-a088-2f636f6af0f0); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@llorllale Take a look now: I've added `type` attribute to XML element so we can specify its type (for now we will just user `array` type, but it could be extended in future). And I've changed XML structure: `array` representions must have ìtem` child objects. This way we can easily parse it.

**Comment by llorllale** [comment]
@paulodamaso there are only two complex types in json: arrays and objects. So a simple boolean attribute similar to what I proposed will suffice. An attribute of type text needlessly introduces extra ambiguity ("what values aside from 'array' and 'object' can this field have?").

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#1444](https://github.com/jcabi/jcabi-github/issues/1444) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
