### PR TITLE
#977 Strange maven configuration

### PR DESCRIPTION
**Pull request by maxim-kornienko**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@longtimeago could you please review this pull request

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@longtimeago Thanks so much! Your account was topped up for **16 mins** (transaction ID is `50573558`)

+16 added to your rating, current score is: [+1231](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
