### PR TITLE
Fix javadoc

### PR DESCRIPTION
**Pull request by SerCeMan**
Fix javadoc

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@pinaf please review this one

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@pinaf thanks, I just added **16 mins** to your account, payment `AP-81B39890J40701346`, 47 hours and 18 mins spent

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+5314](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
