### PR TITLE
Fixed checkstyle errors

### LINKED ISSUE #1503: Fix Qulice errors and release #1502
PR #1502 has been merged, but it contains a few [Qulice errors](https://travis-ci.org/jcabi/jcabi-github/builds/637260143#L2082).
Let's fix them so we can release a new version.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #1503

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor try to merge

**Comment by 0crat** [comment]
Job [#1506](https://github.com/jcabi/jcabi-github/issues/1506) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1506` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1506](https://github.com/jcabi/jcabi-github/issues/1506) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
