### PR TITLE
feat(#1663): Implement `RepositoryStatistics.Smart`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Implement `RepositoryStatistics.Smart` to be able to gather useful statistics from repositories.

Closes: #1663

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1666` is not assigned, can't get performer

**Comment by volodya-lombrozo** [comment]
@yegor256 could you release a new version, please?

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.0`

**Pull request merged**
