### PR TITLE
#1326: upgraded

### PR DESCRIPTION
**Pull request by yegor256**
Versions up.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1327` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3135](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
