### PR TITLE
fix CarefulWire ctor JavaDoc typo: util => until

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@pinaf please review this PR

**Comment by pinaf** [comment]
@cvrebert thanks

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by pinaf** [comment]
@yegor256 let's try to merge again
>
Failed tests: RtReleaseAssetsITCase.returnsNoAssets:259 HTTP response status is not equal to 201: 422 Unprocessable Entity [https://api.github.com/repos/jcabi-github-test2/AgTo8rZjXc/releases] Server: GitHub.com Date: Mon, 13 Apr 2015 21:21:57 GMT Content-Type: application/json; charset=utf-8

**Comment by yegor256** [comment]
@rultor merge

**Comment by pinaf** [comment]
@yegor256 These failures are unrelated. Try again?
>
Failed tests: RtMilestonesITCase.createsNewMilestone:116 HTTP response status is not equal to 201: 500 Internal Server Error [https://api.github.com/repos/jcabi-github-test2/jTG9xY8xQU/milestones] Server: GitHub.com Date: Mon, 13 Apr 2015 23:50:25 GMT Content-Type: application/json; charset=utf-8 Content-Length: 80 Status: 500 Internal Server Error X-RateLimit-Limit: 5000 X-RateLimit-Remaining: 4915

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@pinaf thanks, I just added **19 mins** to your account, payment `AP-26X503707D019572T`, 23 hours and 39 mins spent

review comments (c=4) added as a bonus

+19 to your rating, your total score is [+6886](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
