### PR TITLE
For #1429: Correcting copyright info in all files.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1429: Correcting copyright info in all files.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1431](https://github.com/jcabi/jcabi-github/issues/1431) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1431](https://github.com/jcabi/jcabi-github/issues/1431) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2411324297); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 40 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#1431](https://github.com/jcabi/jcabi-github/issues/1431) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
