### PR TITLE
For #1470: Implemented reaction methods and fixed tests.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1470:
- Implemented `Reaction` support to issue comments;
- Changed test because the prior test wasn't working

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1484](https://github.com/jcabi/jcabi-github/issues/1484) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1484](https://github.com/jcabi/jcabi-github/issues/1484) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/5679cf5b-be46-4dcf-86c1-921707d17c35); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
The job [#1484](https://github.com/jcabi/jcabi-github/issues/1484) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
