### PR TITLE
#987 RtRepo.java:53-54: Uncomment test RtRepoTest.iteratesLanguages()...

### PR DESCRIPTION
**Pull request by maxim-kornienko**

### CODE REVIEW

**Comment by dmarkov** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@krzyk please review this PR

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@krzyk **16 mins** added to your account (payment number `50573610`), many thanks for your contribution!

+16 to your rating, your total score is [+2271](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
