### PR TITLE
Upgrade to xembly 0.21

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 **16 mins** sent to your balance (ID `000-a9bc8fcc`), many thanks! It took 21 hours and 19 mins.. review comments (c=1) added as a bonus. +16 added to your rating, current score is: [+5914](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
