### PR TITLE
(#1306) Added rule in some tests for using random ports for the MkGrizzlyContainer

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* solves #1306 
* Leave puzzle for the rest

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1376](https://github.com/jcabi/jcabi-github/issues/1376) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1376](https://github.com/jcabi/jcabi-github/issues/1376) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C9R53K5JA/941488615); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by amihaiemil** [comment]
@llorllale looks ok

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1376](https://github.com/jcabi/jcabi-github/issues/1376) is now out of scope

**Pull request merged**
