### PR TITLE
(#1400) User.notifications() now returns Notifications instead of List<Notification>

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* solves #1400 
* Entirely refactors test `RtUserTest.notifications()` because behavior for the value returned belongs in `RtNotificationsTest`
* Fixes a couple of unrelated checkstyle issues
* Leaves puzzle for `Repo.notifications()`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1405](https://github.com/jcabi/jcabi-github/issues/1405) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by amihaiemil** [comment]
@llorllale nice, I like it :)

**Comment by 0crat** [comment]
The job [#1405](https://github.com/jcabi/jcabi-github/issues/1405) is now out of scope

**Pull request merged**
